### ISSUE TITLE
output bin range as list element in set_bins

### ISSUE THREAD

**Issue by vjd** [dpastoor/PKPDmisc#23]
set_bins returns the grouping bin number that each `idv` falls into. In most cases, these groups will be on a discrete scale while plotting and hence have to be labelled with bin ranges. e.g concentration range of 10-20 on the x-axis would be better to be labelled as such than as a BinNumber.
Since you are screen printing the range of each bin anyway, it is probably easier to output the range as a pasted text e.g. `10-20` that can be accessed via plotting. This output can either be a list element or a an attribute of the output

**Comment by dpastoor** [comment]
this was done as a new function `set_bins_df` here https://github.com/dpastoor/PKPDmisc/commit/b9fe76b3af52a2ee791f6ddbf66bec0cef5d8385
