### ISSUE TITLE
set_bins requires na.rm

### ISSUE THREAD

**Issue by vjd** [dpastoor/PKPDmisc#26]
I think it is important that `set_bins` option have a `na.rm` option to allow vectors that have NA's to pass through (preferably with a warning)
e.g.

Works fine.
```
foo <- rnorm(100,3,1)
PKPDmisc::set_bins(foo,breaks=quantile(foo,seq(0,1,length.out = 4)))
```
Introduce a NA and it breaks down.
```
foo[3] <- NA
PKPDmisc::set_bins(foo,breaks=quantile(foo,seq(0,1,length.out = 4)))
```
Allow for an option to set the bins by using `na.rm=TRUE`

```
PKPDmisc::set_bins(foo,breaks=quantile(foo,seq(0,1,length.out = 4),na.rm = TRUE))

```

**Comment by dpastoor** [comment]
actually `set_bins` handles na's gracefully

```
foo <- rnorm(10,3,1)
PKPDmisc::set_bins(foo,breaks=quantile(foo,seq(0,1,length.out = 4)))
#>  [1] 1 1 3 2 2 2 3 1 3 4
foo[3] <- NA
PKPDmisc::set_bins(foo,breaks=c(1, 3, 5))
#>  [1]  1  1 NA  2  1  1  2  1  2  3
```

the problem is, the quantile function does not know how to calculate quantiles if there are na's, so you need to pass that to quantile

```
PKPDmisc::set_bins(foo,breaks=quantile(foo,seq(0,1,length.out = 4), na.rm = TRUE))
```

and it works as is

**Comment by vjd** [comment]
Understood. But if you want to do default setting of `set_bins` as `set_bins(foo)`, then it will definitely error out. In this case it uses the `breaks` and hence does not allow a `NA` vector to pass through and provides no option to add `na.rm=TRUE`

**Comment by dpastoor** [comment]
I'd prefer to keep the na.rm out of set_bins itself, as that is related to the quantile calculation, not set_bins (eg na.rm for set bins would need to actually filter the rows). What I have done, is changed the default now to quantile(x, na.rm=T) so using the default is more robust in 088ff654cb2fdade1ed769d854e230873efa261d

Thanks for the pickup!
