### ISSUE TITLE
base_theme & char_to_numeric

### ISSUE THREAD

**Issue by aalhadab** [dpastoor/PKPDmisc#27]
when I change the font size in base_theme, the plot is cut off.  char_to_numeric dose not convert columns to numeric when variable is factor

**Comment by dpastoor** [comment]
Hi aalhadab. When changing the font size, the plot being cut off is not anything base_theme() is doing, that is likely the fault of ggplot itself. If you give a reproducible example (for example using the Theoph dataset) I can likely try to help figure it out. 

For char_to_numeric, the function is meant, as of now, to only handle character columns. Instead I suggest you use the function `as_numeric()` which will coerce any column to numeric by first turning it into a character column the numeric for cases where you have factor columns. Note that as_numeric is meant for single columns so you'd do something like

```
library(dplyr)
# Subject is a factor column in Theoph
Theoph %>% mutate(num_sub = as_numeric(Subject))
```

If you want to coerce all columns to numeric, you can instead use the `purrr` library (newer package by hadley), which has a very nifty function called `map_if`

```
# for any columns that are factor, apply the function as_numeric to them
Theoph %>% map_if(is.factor, as_numeric) %>% as_data_frame
```
