### ISSUE TITLE
[F] chunk_list

### ISSUE THREAD

**Issue by kylebmetrum** [dpastoor/PKPDmisc#33]
I'm not sure if there is an easy way to chunk up a list or vector a la `chunk_df`.  I can submit PR if not. 

Something like
```r
> chunk_list(seq(1:41), .nchunks = 3)
[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14

[[2]]
 [1] 15 16 17 18 19 20 21 22 23 24 25 26 27 28

[[3]]
 [1] 29 30 31 32 33 34 35 36 37 38 39 40 41
```

**Comment by dpastoor** [comment]
would you want the chunks to be naively equally sized, or actually based on unique values so so you'd get ragged vectors but equal number of unique values within each?

**Comment by kylebmetrum** [comment]
Just naively-sized.  It'd be for parallel applications where I have a list of jobs that needs to get done (1 through 41) and I want to split them across 3 cores

```r
##' Chunk lists or vectors so easy to split for parallel processing
##' 
##' @param .list a list or vector to chunk
##' @param .nchunks set number of chunks
##' 
##' @examples
##' chunk_list(seq(0,100))
##' 
##' @export
chunk_list <- function(.list, .nchunks = NULL) {
  if(is.null(.nchunks)) {
    .nchunks <- parallel::detectCores() 
  }
  num_indices <- length(.list)
  per_chunk <- num_indices %/% .nchunks
  remainder <- num_indices %% .nchunks
  if (remainder > 0) {
    chunk_indices <- c(rep(1:.nchunks, per_chunk), 1:remainder)
  } else {
    chunk_indices <- rep(1:.nchunks, per_chunk)
  }
  chunk_indices <- chunk_indices[order(chunk_indices)]
  unname(split(.list,chunk_indices))
}

```

**Comment by dpastoor** [comment]
how about these functions

we have chunk/chunk_grp which will give back the chunk index associated with each

then <c>_list versions give back a list with the values inside rather than the indices - looks like your function above was basically the exact same thing

**Comment by kylebmetrum** [comment]
Yeah ... I wrote my function to behave along similar lines as `chunk_df`.

**Comment by dpastoor** [comment]
done in #34 - let me know if you'd like any other versions
